// Copyright 2018-2022 the Deno authors. All rights reserved. MIT license.
// This module is browser compatible.
/**
 * A parsed path object generated by path.parse() or consumed by path.format().
 */ 